.TH "USOCK-SERVER" "1" "19/12/2016" "\ \&" "\ \&"
.nh
.ad l
.SH "NAME"
usock-server \- communication lib test (usock.c)
.SH "SYNOPSIS"
.sp
\fBusock-server\fR
.SH "DESCRIPTION"
.sp
\fBusock-server\fR is about regression tests of the communication library.
It acts as a simple unix socket server waiting a connection from a client, it then waits for a message and sends it back before quitting.
.sp
This program has currently no options.
.SH "SEE ALSO"
.sp
\fBusock-client\fR(1)
.SH "BUGS"
.sp
Thanks to report bugs to karchnu+bugs@karchnu.fr
.SH "AUTHORS"
.sp
Philippe PITTOLI
.SH "WWW"
.sp
\fBhttps://git.karchnu.fr/Karchnu/perfectos-junk
